macro(verifyOneOf _retVal)
    set(oneSet FALSE)
    foreach (option ${ARGN})
        if (NOT ${oneSet})
            set(oneSet ${option})
        else(NOT ${oneSet})
            if (${option})
                set(_retVal FALSE)
                return()
            endif(${option})
        endif (NOT ${oneSet})
    endforeach (option ${ARGN})

    set(_retVal ${oneSet})
endmacro(verifyOneOf)
